@php
    $badgeClasses = [
        'APPROVED' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'REVISION' => 'bg-amber-subtle text-amber-emphasis border border-amber-subtle',
        'REJECTED' => 'bg-rose-subtle text-danger border border-rose-subtle',
        'SUBMITTED' => 'bg-indigo-subtle text-primary border border-indigo-subtle',
        'REQUESTED' => 'bg-indigo-subtle text-primary border border-indigo-subtle',
        'WAITING_APPROVAL' => 'bg-cyan-subtle text-cyan-emphasis border border-cyan-subtle',
        'WAITING_EXAMINER' => 'bg-amber-subtle text-amber-emphasis border border-amber-subtle',
        'READY_TO_SCHEDULE' => 'bg-indigo-subtle text-primary border border-indigo-subtle',
        'SCHEDULED' => 'bg-indigo-subtle text-primary border border-indigo-subtle',
        'FINISHED' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'REVIEW' => 'bg-cyan-subtle text-cyan-emphasis border border-cyan-subtle',
        'DRAFT' => 'bg-light text-muted border',
        'PUBLISHED' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'ONGOING' => 'bg-cyan-subtle text-cyan-emphasis border border-cyan-subtle',
        'WAITING' => 'bg-light text-muted border',
        'PENDING' => 'bg-light text-muted border',
        'APPROVED_BY_SUPERVISORS' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'PASSED' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'PASSED_WITH_REVISION' => 'bg-amber-subtle text-amber-emphasis border border-amber-subtle',
        'REPEAT' => 'bg-rose-subtle text-danger border border-rose-subtle',
        'SEMINAR_PASSED' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'SEMINAR_REPEAT' => 'bg-rose-subtle text-danger border border-rose-subtle',
        'OPEN' => 'bg-amber-subtle text-amber-emphasis border border-amber-subtle',
        'DONE' => 'bg-emerald-subtle text-success border border-emerald-subtle',
        'WAITING_VALIDATION' => 'bg-amber-subtle text-amber-emphasis border border-amber-subtle',
        'READY_FOR_DEFENSE' => 'bg-indigo-subtle text-primary border border-indigo-subtle',
        'REVISION_AFTER_SEMINAR' => 'bg-amber-subtle text-amber-emphasis border border-amber-subtle',
        'FINAL_REPORT' => 'bg-indigo-subtle text-primary border border-indigo-subtle',
    ];

    $icons = [
        'APPROVED' => 'bi-check-circle-fill',
        'WAITING_VALIDATION' => 'bi-hourglass-split',
        'READY_FOR_DEFENSE' => 'bi-flag-fill',
        'REVISION_AFTER_SEMINAR' => 'bi-pencil-square',
        'FINAL_REPORT' => 'bi-file-earmark-text-fill',
        'REVISION' => 'bi-exclamation-circle-fill',
        'REJECTED' => 'bi-x-circle-fill',
        'SUBMITTED' => 'bi-send-fill',
        'REQUESTED' => 'bi-send-fill',
        'WAITING_APPROVAL' => 'bi-clock-fill',
        'WAITING_EXAMINER' => 'bi-hourglass-split',
        'READY_TO_SCHEDULE' => 'bi-calendar-check-fill',
        'SCHEDULED' => 'bi-calendar-event-fill',
        'FINISHED' => 'bi-check-square-fill',
        'REVIEW' => 'bi-search',
        'DRAFT' => 'bi-pencil-fill',
        'PUBLISHED' => 'bi-calendar-check-fill',
        'ONGOING' => 'bi-play-circle-fill',
        'WAITING' => 'bi-clock',
        'PENDING' => 'bi-clock',
        'APPROVED_BY_SUPERVISORS' => 'bi-check-circle-fill',
        'PASSED' => 'bi-award-fill',
        'PASSED_WITH_REVISION' => 'bi-pencil-square',
        'REPEAT' => 'bi-x-circle-fill',
        'SEMINAR_PASSED' => 'bi-award-fill',
        'SEMINAR_REPEAT' => 'bi-x-circle-fill',
        'OPEN' => 'bi-card-text',
        'DONE' => 'bi-check-circle-fill',
    ];
@endphp
<span class="badge {{ $badgeClasses[$status] ?? 'bg-light text-dark border' }}">
    <i class="bi {{ $icons[$status] ?? 'bi-dot' }} me-1"></i>{{ $status }}
</span>

